{"name": "Если создаем курьера без пароля, возвращается ошибка", "status": "passed", "start": 1716882329465, "stop": 1716882329520, "uuid": "7502e44e-7553-4b69-95db-d6d431d2ea05", "historyId": "0839e62a554267b645da8e32407dd0ac", "testCaseId": "0839e62a554267b645da8e32407dd0ac", "fullName": "tests.test_create_courier#test_message_create_courier_without_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "host", "value": "MBP-Olga"}, {"name": "thread", "value": "5325-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}